site_name: DOCUMENTAÇÃO - GRUPO 5
repo_url: https://github.com/Requisitos-de-Software/2024.2-Grupo05

extra_css:
  - stylesheets/style.css
nav: 
  - Home: index.md
  - Atas:
    - Ata1: Atas/ata01.md
theme: 
  name: material
  font:
    text: IBM Plex Serif
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
icon:
  repo: fontawesome/brands/git-alt